version: '3.8'

services:
  web:
    container_name: web
    build: 
      context: .
    command: ./encryption.sh
    ports:
      - "8000:8000"
    volumes:
      - ".:/app"
    networks:
      - webnet
    depends_on:
      - db

  db:
    container_name: postgres
    image: postgres:16
    networks:
      - webnet
    volumes:
      - "./postgres_data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root

networks:
    webnet: